### ISSUE TITLE
EasyRdf with schema.org

### ISSUE THREAD

**Issue by Jonadabe** [alexprut/Spider4Schema#1]
Hi there,

I don't know if the end result of the json file is what you want, but I think you could try using http://www.easyrdf.org/converter with the link http://schema.org/docs/schema_org_rdfa.html

Just a thought.

**Comment by alexprut** [comment]
@Jonadabe I've tried but it doesn't produce an ordered and clean JSON format, which means I need to work on it anyway, that's the end result I wanna obtain [https://github.com/PAlexcom/Spider4Schema/blob/master/dist/types.json](https://github.com/PAlexcom/Spider4Schema/blob/master/dist/types.json). (maybe I'm doing something wrong?)
